### ISSUE TITLE
Audio glitches and low volume

### ISSUE THREAD

**Issue by joerick** [googlecodelabs/androidthings-googleassistant#3]
Hi guys, got this working but I think there's a problem with audio.

After asking a question, the speaker pops loudly (as if it's powering on) and the response voice is very quiet. This is running the 'step2-volume-control' code. I've recorded a video to demonstrate. 

[![](https://dn878zrhv1uso.cloudfront.net/production/2A422X0L3R21/thumbs_01.jpg) Video](https://cl.ly/2A422X0L3R21)

The same hardware running the Raspbian-based Python code has no issues. I've also attached a [full log of one question/response](https://pastebin.com/raw/j3r4NApF), there are some audio-related errors in there, but I couldn't say for sure that they're related.

Thanks, 
Joe

**Comment by Fleker** [comment]
Can you remove the LED blinking in the audio response and see if that works?

Can you verify that the speaker hardware is connected well?

**Comment by joerick** [comment]
I've just double-checked and the connections look good, and the AIY demo works great.

I disabled blinking (by removing the `mLed` initialization code), but that doesn't seem to make a difference. I see there are some more changes on master, I'll try them now.

**Comment by Fleker** [comment]
Does this problem occur with all three steps, or just the second?

**Comment by joerick** [comment]
All three

**Comment by Fleker** [comment]
Do you experience the same behavior if you try with the [Google Assistant sample](https://github.com/androidthings/sample-googleassistant)?

I have not seen this kind of behavior before, but if it's consistent on all versions of this code then it should be easily reproducible.

**Comment by joerick** [comment]
Apologies, I'll have to revisit this in the new year, I've left it at work, and I'm away for Christmas!

**Comment by leon1101** [comment]
I just assembled a brand new kit, flashed the latest version of Android Things and loaded the Google Assistant sample. It works, but I'm having the same low-volume and cracking audio issue.

**Comment by almighty972** [comment]
Hello, same issue for me regarding the low-volume .
I used the sample-googleassistant (master branch).
By the way, I didn't found any branch with the v1alpha2 version of the google assistant proto models, so I had to upgrade to the v1alpha2 embedded proto.

For the low volume, I tried to use the adb shell service call audio 3 i32 3 i32 100 i32 1 (based on Oreo android.media.IAudioService interface) but nothing has changed.

**Comment by ashdavies** [comment]
I'm having the low volume issue, but I'm not sure at what point it started, on the first assembly it was fine, then after getting the wifi sorted and trying again it's super quiet.

**Comment by pcarff** [comment]
I am having the same audio issues and crackling.  I build the [Raspbian version](https://github.com/google/aiyprojects-raspbian/tree/voicekit) and the audio was awesome.  Using the same hardware I changed out the SD card with Android Things and am now having audio issues.

**Comment by amardeepjaiman** [comment]
I am also facing the same issue on Android things version 0.6 preview. On raspbian version the sound is fine. But on android things its very low.

**Comment by Fleker** [comment]
You should be able to tweak the volume using the code in Step 2.

**Comment by ashdavies** [comment]
@Fleker tweak the volume to more than 100% ?

**Comment by amardeepjaiman** [comment]
step2 ?

**Comment by pflammertsma** [comment]
@Fleker The problem is not the output volume of Google Assistant; it's the output of the speaker itself. Performing a test with the `step2-volume-control` module, the _initial volume is max_, yet it's played so quietly it can almost not be heard except in a completely quiet environment.

Nevertheless, I've tried your suggestion, instructing it to set max volume:

```
02-15 10:19:42.410 1393-1393/com.example.androidthings.assistant I/AssistantActivity: setting volume to: 15
02-15 10:20:04.521 1393-1449/com.example.androidthings.assistant I/AssistantActivity: assistant request text: set the volume to max
02-15 10:20:04.556 1393-1449/com.example.androidthings.assistant I/AssistantActivity: assistant volume changed: 100
```

Indeed this had no effect.

I've tried the following myself:
- Booting into Raspbian and testing the [AIY Voice Kit](https://github.com/google/aiyprojects-raspbian); as others have pointed out, the ALSA drivers play sound very loud over the speaker. I did not adjust the hardware in any way between Raspbian and Android Things.
- I wrote a simple project that plays a generated tone using the Voice HAT pin assignments over a Max98357A (so using BCM16). I generated the tone at max volume, playing at 16 bit PCM with the waveform from -32768 to 32767. Testing the AudioTrack logic on my phone this is so loud I'm worried it damages the speaker. On the AIY kit running Android Things, it's again extremely quiet.
- I looked into the AIY implementation, thinking perhaps the amp needs to be powered, but as I pointed out in issue #54: [a comment in `VoiceHat.openDac()`](https://github.com/androidthings/contrib-drivers/blob/master/voicehat/src/main/java/com/google/android/things/contrib/driver/voicehat/VoiceHat.java#L123) specifically states:
> On the VoiceHat, the GAIN_SLOT pin on the DAC is not connected.

I've only tested using a Raspberry Pi 3 running iot_rpi3 0.6.1-devpreview (Android 8.1.0).

**Comment by Fleker** [comment]
Maybe the issue is relating to the data being sent from the board over the I2S line. If it's not being sent at a high volume it will not be rendered very loud when the peripheral receives the data either.

**Comment by pflammertsma** [comment]
How can I troubleshoot the data being sent? From the Android SDK side, I've set the AudioTrack volume to max as well as producing a waveform at maximum amplitude.

In the meantime I have purchased a separate Max98357 amp and will wire this tomorrow. If it exhibits the same behavior, at least this way I can attempt enabling gain (as the Voice HAT's gain pin isn't even attached to the solder point).

**Comment by pflammertsma** [comment]
To be clear, the following volume related fields are set.

On the AudioTrack:  
    audioTrack?.setVolume(AudioTrack.getMaxVolume())

On the AudioManager:
    val manager = this.getSystemService(Context.AUDIO_SERVICE) as AudioManager
    manager.setStreamVolume(AudioManager.STREAM_MUSIC,
            manager.getStreamMaxVolume(AudioManager.STREAM_MUSIC), 0)

On the PCM waveform:
    val valueShort = (Math.sin(j.toFloat() / steps.toFloat() * Math.PI * 2f) * Short.MAX_VALUE).toInt()
    recordedBytes.put((valueShort shr 8 and 0xFF).toByte())
    recordedBytes.put((valueShort and 0xFF).toByte())

I don't think the output volume is the problem here as if there's something wrong with the sample, surely all devices would exhibit the same behavior. Does it play loudly for you, @Fleker?

**Comment by Fleker** [comment]
I've been talking with some other engineers about a potential fix based on the way that audio is handled in Android. I'll be taking a look at this again, as well as a potential fix, today or tomorrow.

The implementation is the sample for both the codelab and sample, so we can use the issue in the sample to discuss this shared issue.

https://github.com/androidthings/sample-googleassistant/issues/54
